In [10]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

data = pd.read_csv('../input/19560-indian-takeaway-orders/restaurant-1-orders.csv')
data.head()

,Order Number,Order Date,Item Name,Quantity,Product Price,Total products
0,16118,03/08/2019 20:25,Plain Papadum,2,0.80,6
1,16118,03/08/2019 20:25,King Prawn Balti,1,12.95,6
2,16118,03/08/2019 20:25,Garlic Naan,1,2.95,6
3,16118,03/08/2019 20:25,Mushroom Rice,1,3.95,6
4,16118,03/08/2019 20:25,Paneer Tikka Masala,1,8.95,6

In [11]:
data.shape

(74818, 6)

In [12]:
data.isnull().count()

Order Number      74818
Order Date        74818
Item Name         74818
Quantity          74818
Product Price     74818
Total products    74818
dtype: int64

In [13]:
data_basket = (data.groupby(['Order Number', 'Item Name'])['Quantity']
              .sum().unstack().reset_index().fillna(0)
              .set_index('Order Number'))

In [18]:
data_basket.head()

Item Name,Aloo Chaat,Aloo Gobi,Aloo Methi,Baingan Hari Mirch,Bengal Fish Biryani,Bengal Fish Karahi,Bengal Fry Fish,Bengal King Prawn,Bengal Salad,Bhindi Bhajee,...,Vegetable Rice,Vegetable Roll,Vegetable Samosa,Vindaloo,Vindaloo - Chicken,Vindaloo - Chicken Tikka,Vindaloo - King Prawn,Vindaloo - Lamb,Vindaloo - Prawn,Vindaloo Sauce
Order Number,,,,,,,,,,,,,,,,,,,,,
630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
647,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
648,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
764,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
data_basket.shape

(13397, 248)

In [52]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [53]:
data_basket.columns

Index(['Aloo Chaat', 'Aloo Gobi', 'Aloo Methi', 'Baingan Hari Mirch',
       'Bengal Fish Biryani', 'Bengal Fish Karahi', 'Bengal Fry Fish',
       'Bengal King Prawn', 'Bengal Salad', 'Bhindi Bhajee',
       ...
       'Vegetable Rice', 'Vegetable Roll', 'Vegetable Samosa', 'Vindaloo',
       'Vindaloo - Chicken', 'Vindaloo - Chicken Tikka',
       'Vindaloo - King Prawn', 'Vindaloo - Lamb', 'Vindaloo - Prawn',
       'Vindaloo Sauce'],
      dtype='object', name='Item Name', length=248)

In [54]:
data_basket_sets = data_basket.applymap(encode_units)

data_basket_sets

Item Name,Aloo Chaat,Aloo Gobi,Aloo Methi,Baingan Hari Mirch,Bengal Fish Biryani,Bengal Fish Karahi,Bengal Fry Fish,Bengal King Prawn,Bengal Salad,Bhindi Bhajee,...,Vegetable Rice,Vegetable Roll,Vegetable Samosa,Vindaloo,Vindaloo - Chicken,Vindaloo - Chicken Tikka,Vindaloo - King Prawn,Vindaloo - Lamb,Vindaloo - Prawn,Vindaloo Sauce
Order Number,,,,,,,,,,,,,,,,,,,,,
630,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
648,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
651,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
764,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16116,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
data_basket_sets.shape

(13397, 248)

In [56]:
freq_itemset = apriori(data_basket_sets, min_support=0.1, use_colnames=True)
freq_itemset.shape

(16, 2)

In [50]:
freq_itemset

     support                        itemsets
0   0.130776                   (Bombay Aloo)
1   0.159215          (Chicken Tikka Masala)
2   0.196163                   (Garlic Naan)
3   0.101665                    (Keema Naan)
4   0.154438                 (Mango Chutney)
5   0.109204                    (Mint Sauce)
6   0.108382                 (Mushroom Rice)
7   0.179219                  (Onion Bhajee)
8   0.114578                 (Peshwari Naan)
9   0.352392                    (Pilau Rice)
10  0.280063                    (Plain Naan)
11  0.268418                 (Plain Papadum)
12  0.176831                    (Plain Rice)
13  0.113010  (Plain Papadum, Mango Chutney)
14  0.129133        (Plain Naan, Pilau Rice)
15  0.133239     (Plain Papadum, Pilau Rice)

In [57]:
rules = association_rules(freq_itemset, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Plain Papadum),(Mango Chutney),0.268418,0.154438,0.113010,0.421023,2.726172,0.071557,1.460443
1,(Mango Chutney),(Plain Papadum),0.154438,0.268418,0.113010,0.731754,2.726172,0.071557,2.727284
2,(Plain Naan),(Pilau Rice),0.280063,0.352392,0.129133,0.461087,1.308449,0.030441,1.201693
3,(Pilau Rice),(Plain Naan),0.352392,0.280063,0.129133,0.366448,1.308449,0.030441,1.136350
4,(Plain Papadum),(Pilau Rice),0.268418,0.352392,0.133239,0.496385,1.408614,0.038650,1.285918
5,(Pilau Rice),(Plain Papadum),0.352392,0.268418,0.133239,0.378098,1.408614,0.038650,1.176361